Update README.md
RotonEvan/covidvsindia pull request #1
Opened 2020-09-30 14:17 UTC by debrajhyper

2020-10-01 13:51 UTC, RotonEvan requested changes
If you want to update the readme properly you might want to add a few more lines on the purpose of the repo

2020-10-02 06:45 UTC, debrajhyper commented
okay

2020-10-02 06:53 UTC, debrajhyper reviewed
it is updated.

2020-10-02 08:46 UTC, RotonEvan approved these changes
Accepted. Thanks for the update !

2020-10-02 08:47 UTC, merged